[package]
name = "wasmdbg"
version = "0.1.0"
authors = ["Benedikt Werner <1benediktwerner@gmail.com>"]
edition = "2018"

[dependencies]
parity-wasm = "0.38"
clap = "2.33.0"
colored = "1.8"
rustyline = "5.0.0"
shellexpand = "1.0.0"
lazy_static = "1.3.0"
